# Generated by Django 5.1.1 on 2024-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_options_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
